require "rake/testtask"

task :default => :test
task :pc => %w[test gemspec:generate]

task :test => %w[test:unit test:acceptance]
namespace :test do
  Rake::TestTask.new(:acceptance) do |t|
    t.pattern = "test/acceptance/**/*_test.rb"
  end

  Rake::TestTask.new(:unit) do |t|
    t.pattern = "test/unit/**/*_test.rb"
  end
end

gem_spec = Gem::Specification.new do |s|
	s.name   = "xcodeprojgen"
  s.summary = "generates xcodeproj files"
	s.version = "0.1.1"
	s.author = "Dan Manges"
	s.description = s.summary
	s.email = "daniel.manges@gmail.com"
  s.homepage = "http://github.com/framework-x/xcodeprojgen"
  # s.rubyforge_project = "xcodeprojgen"
  
  s.has_rdoc = false
  
  s.executables = %w[xcodeprojgen]
  s.files = FileList['{bin,lib,test}/**/*.rb', 'TODO', 'README.markdown', 'Rakefile'].to_a
end

task :gem => %w[test] do
  Gem::Builder.new(gem_spec).build
end

namespace :gemspec do
  desc "generates xcodeprojgen.gemspec"
  task :generate do
    File.open("xcodeprojgen.gemspec", "w") do |f|
      f.puts "# this file is generated by rake gemspec:generate for github"
      f.write gem_spec.to_ruby
    end
  end
end
