# this file is generated by rake gemspec:generate for github
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{xcodeprojgen}
  s.version = "0.1.0"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Dan Manges"]
  s.date = %q{2009-05-09}
  s.default_executable = %q{xcodeprojgen}
  s.description = %q{generates xcodeproj files}
  s.email = %q{daniel.manges@gmail.com}
  s.executables = ["xcodeprojgen"]
  s.files = ["lib/xcode/frameworks.rb", "lib/xcode/iphone.rb", "lib/xcode/iphone_build_configurations.rb", "lib/xcode/pbx_build_file.rb", "lib/xcode/pbx_build_phase.rb", "lib/xcode/pbx_copy_files_build_phase.rb", "lib/xcode/pbx_file_reference.rb", "lib/xcode/pbx_formatter.rb", "lib/xcode/pbx_frameworks_build_phase.rb", "lib/xcode/pbx_group.rb", "lib/xcode/pbx_native_target.rb", "lib/xcode/pbx_proj.rb", "lib/xcode/pbx_project.rb", "lib/xcode/pbx_resources_build_phase.rb", "lib/xcode/pbx_sources_build_phase.rb", "lib/xcode/xc_build_configuration.rb", "lib/xcode/xc_configuration_list.rb", "lib/xcode.rb", "lib/xcodeproj_gen.rb", "test/acceptance/command_line_foundation_test.rb", "test/acceptance/command_line_in_c_test.rb", "test/acceptance/test_helper.rb", "test/unit/test_helper.rb", "test/unit/xcode/pbx_build_file_test.rb", "test/unit/xcode/pbx_build_phase_test.rb", "test/unit/xcode/pbx_file_reference_test.rb", "test/unit/xcode/pbx_formatter_test.rb", "test/unit/xcode/pbx_group_test.rb", "test/unit/xcode/pbx_native_target_test.rb", "test/unit/xcode/pbx_project_test.rb", "test/unit/xcode/xc_build_configuration_test.rb", "test/unit/xcode/xc_configuration_list_test.rb", "test/unit/xcode_test.rb", "TODO", "README.markdown", "Rakefile", "bin/xcodeprojgen"]
  s.homepage = %q{http://github.com/framework-x/xcodeprojgen}
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.1}
  s.summary = %q{generates xcodeproj files}

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 2

    if Gem::Version.new(Gem::RubyGemsVersion) >= Gem::Version.new('1.2.0') then
    else
    end
  else
  end
end
